### Numpy
- python에서 사용하는 과학계산용 패키지
- Python의 느린 연산속도를 보완
- ndarry 데이터 타입의 배열 객체로 연산
- C, C++, 포트란으로 만들어짐

In [1]:
import numpy as np

#### 1. ndarray 객체 생성
- list와 ndarray의 다른점
    - list는 서로 다른 데이터 타입을 사용 가능
    - ndarray는 같은 데이터 타입만 사용이 가능
    - 연산하는 방법이 다릅니다.

In [5]:
ls = [1, 2, 3]
arr = np.array(ls)

type(ls), type(arr), ls, arr

(list, numpy.ndarray, [1, 2, 3], array([1, 2, 3]))

In [7]:
ls + ls, arr + arr

([1, 2, 3, 1, 2, 3], array([2, 4, 6]))

In [8]:
# 선형대수
# 스칼라(5), 벡터([1, 2, 3]), 매트릭스([[1, 2, 3], [4, 5, 6]])

In [13]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]]) 
arr, arr2

(array([1, 2, 3]),
 array([[1, 2, 3],
        [4, 5, 6]]))

In [12]:
# 배열의 차원 확인
arr.ndim, arr2.ndim

(1, 2)

In [14]:
# 배열의 모양을 확인
arr.shape, arr2.shape

((3,), (2, 3))

In [16]:
arr3 = np.array(list("ABCD"))
arr3

array(['A', 'B', 'C', 'D'], dtype='<U1')

In [18]:
# 배열의 데이터 타입 확인
arr.dtype, arr3.dtype

(dtype('int64'), dtype('<U1'))

In [24]:
# 데이터 타입의 변경
arr4 = arr.astype(np.float32)
arr4.dtype

dtype('float32')

In [25]:
# np.arange()
# range와 같은 규칙을 갖습니다. 
# 결과 데이터가 ndarray 데이터 타입입니다.

In [26]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [27]:
np.arange(5, 8)

array([5, 6, 7])

In [29]:
np.arange(1, 8, 2)

array([1, 3, 5, 7])

In [30]:
# np.zeros() : 0으로 채워진 행렬 데이터를 생성
# np.ones() : 1로 채워진 행렬 데이터를 생성

In [33]:
zero_data = np.zeros((2, 2, 3))
zero_data

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [34]:
one_data = np.ones((2, 2, 3))
one_data

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### np.random
- rand() : 균등분포로 난수 발생
- randn() : 정규분포로 난수 발생
- randint() : 정수로 난수 발생(균등분포)

In [35]:
# 균등분포 : uniform : 0 ~ 1 사이의 float 데이터
data = np.random.rand(10)
data

array([0.7052242 , 0.76840205, 0.69672647, 0.42561231, 0.08733437,
       0.14647136, 0.97542304, 0.7307141 , 0.49821657, 0.74702739])

In [37]:
# 정규분포 : gaussian : 0을 기준으로 float 데이터
data = np.random.randn(10)
data

array([-1.47974709, -0.04230415, -1.53377696, -0.14889449, -1.3473551 ,
       -0.25096975,  0.61675557,  1.62106347, -1.36553644,  0.57860463])

In [38]:
# randint : 정수 데이터 타입을 균등분포로 생성

In [67]:
np.random.randint(5, size=(2, 3))

array([[2, 2, 4],
       [1, 1, 1]])

In [74]:
np.random.randint(-3, 5, (2, 3))

array([[ 1, -3,  1],
       [-3, -3,  1]])

In [76]:
# seed()
# numpy의 랜덤값은 seed 값으로 생성 합니다.
# seed 값이 같으면 동일한 랜덤값이 출력됩니다.

In [77]:
np.random.seed(1)
data1 = np.random.randint(0, 100, 10)

np.random.seed(1)
data2 = np.random.randint(0, 100, 10)

np.random.seed(2)
data3 = np.random.randint(0, 100, 10)

data1, data2, data3

(array([37, 12, 72,  9, 75,  5, 79, 64, 16,  1]),
 array([37, 12, 72,  9, 75,  5, 79, 64, 16,  1]),
 array([40, 15, 72, 22, 43, 82, 75,  7, 34, 49]))

In [79]:
# choice()
# 특정 범위의 데이터를 랜덤하게 선택하는데 확률 설정이 가능
# 확률 데이터는 모두 합쳤을때 1이 되어야 합니다.

In [86]:
np.random.choice(5, 10, p=[0.1, 0.0, 0.5, 0.2, 0.2])

array([2, 0, 4, 2, 2, 2, 2, 2, 4, 3])

#### 2. ndarray 객체에서 데이터 선택

In [88]:
data = np.random.randint(5, size=(3, 3))
data

array([[3, 1, 4],
       [2, 3, 0],
       [0, 2, 4]])

In [91]:
data[1], data[1][2], data[1, 2]

(array([2, 3, 0]), 0, 0)

In [92]:
data2 = np.random.randint(10, size=10)
data2

array([4, 2, 9, 7, 1, 9, 2, 1, 0, 7])

In [97]:
data2[:3], data2[-3:], data2[::-2]

(array([4, 2, 9]), array([1, 0, 7]), array([7, 1, 9, 7, 2]))

In [101]:
data

array([[3, 1, 4],
       [2, 3, 0],
       [0, 2, 4]])

In [99]:
data[1:]

array([[2, 3, 0],
       [0, 2, 4]])

In [102]:
data[1:][1:], data[1:, 1:]

(array([[0, 2, 4]]),
 array([[3, 0],
        [2, 4]]))

#### 3. ndarray에서 데이터 수정

In [103]:
data2

array([4, 2, 9, 7, 1, 9, 2, 1, 0, 7])

In [105]:
data2[3] = 10
data2

array([ 4,  2,  9, 10,  1,  9,  2,  1,  0,  7])

In [107]:
# vector = vector
data2[3:6] = [11, 12, 13]
data2

array([ 4,  2,  9, 11, 12, 13,  2,  1,  0,  7])

In [109]:
# vector = scala > broadcasting
data2[3:6] = 20
data2

array([ 4,  2,  9, 20, 20, 20,  2,  1,  0,  7])

In [110]:
data

array([[3, 1, 4],
       [2, 3, 0],
       [0, 2, 4]])

In [113]:
# matrix = matrix
data[1:, 1:] = [[11, 12], [13, 14]]
data

array([[ 3,  1,  4],
       [ 2, 11, 12],
       [ 0, 13, 14]])

In [115]:
# matrix = vector
data[1:, 1:] = [21, 22]
data

array([[ 3,  1,  4],
       [ 2, 21, 22],
       [ 0, 21, 22]])

In [116]:
# matrix = scala
data[1:, 1:] = 30
data

array([[ 3,  1,  4],
       [ 2, 30, 30],
       [ 0, 30, 30]])

In [117]:
# reshape() : 배열의 차원 변경

In [130]:
data = np.random.randint(10, size=(3, 4))
data

array([[1, 8, 6, 8],
       [1, 5, 7, 0],
       [9, 1, 5, 9]])

In [131]:
data.reshape(2, 2, 3)

array([[[1, 8, 6],
        [8, 1, 5]],

       [[7, 0, 9],
        [1, 5, 9]]])

In [132]:
data.reshape(4, -1)

array([[1, 8, 6],
       [8, 1, 5],
       [7, 0, 9],
       [1, 5, 9]])

In [134]:
np.zeros_like(data), np.ones_like(data)

(array([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]),
 array([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]))

In [135]:
# ndarray의 연산

In [138]:
data1 = np.array([1, 2, 3])
data2 = np.array([1, 2, 3, 4])
data3 = np.random.randint(5, size=(4, 3))

In [139]:
data1, data2, data3

(array([1, 2, 3]),
 array([1, 2, 3, 4]),
 array([[3, 3, 2],
        [4, 0, 3],
        [0, 0, 4],
        [1, 3, 3]]))

In [140]:
data3 + data1

array([[4, 5, 5],
       [5, 2, 6],
       [1, 2, 7],
       [2, 5, 6]])

In [146]:
data2.reshape(-1, 1)

array([[1],
       [2],
       [3],
       [4]])

In [147]:
data3

array([[3, 3, 2],
       [4, 0, 3],
       [0, 0, 4],
       [1, 3, 3]])

In [148]:
data3 + data2.reshape(4, 1)

array([[4, 4, 3],
       [6, 2, 5],
       [3, 3, 7],
       [5, 7, 7]])

In [149]:
# 비교연산 : masking : [] > 필터링 기능

In [150]:
data3

array([[3, 3, 2],
       [4, 0, 3],
       [0, 0, 4],
       [1, 3, 3]])

In [151]:
data3 >= 2

array([[ True,  True,  True],
       [ True, False,  True],
       [False, False,  True],
       [False,  True,  True]])

In [152]:
data3[data3 >= 2]

array([3, 3, 2, 4, 3, 4, 3, 3])

In [153]:
data3[data3 >= 2] = 10
data3

array([[10, 10, 10],
       [10,  0, 10],
       [ 0,  0, 10],
       [ 1, 10, 10]])

In [154]:
# np.where(condition, True, False)
data = np.random.randint(10, size=(2, 3))
data

array([[3, 2, 6],
       [5, 5, 2]])

In [155]:
np.where(data < 5, 0, 10)

array([[ 0,  0, 10],
       [10, 10,  0]])

In [156]:
# 논리 연산
# all : and : 행렬 데이터를 비교 연산한 결과가 하나라도 False이면 False
# any : or  : 행렬 데이터를 비교 연산한 결과가 하나라도 True이면 True

In [157]:
data1 = np.array([1, 2, 3])
data2 = np.array([1, 2, 3])
data3 = np.array([1, 0, 3])

data1, data2, data3

(array([1, 2, 3]), array([1, 2, 3]), array([1, 0, 3]))

In [158]:
data1 == data2, data1 == data3

(array([ True,  True,  True]), array([ True, False,  True]))

In [159]:
np.all(data1 == data2), np.all(data1 == data3)

(True, False)

In [160]:
np.any(data1 == data2), np.any(data1 == data3)

(True, True)

In [161]:
data = np.random.randint(10, size=(3, 4))
data

array([[5, 6, 1, 5],
       [0, 5, 4, 8],
       [3, 7, 5, 9]])

In [ ]:
# 8이상인 데이터가 있는 row 만 출력

In [163]:
data >= 8

array([[False, False, False, False],
       [False, False, False,  True],
       [False, False, False,  True]])

In [175]:
# axis : 1(가로축), 0(세로축)
row = np.any(data >= 8, axis=1)
row

array([False,  True,  True])

In [176]:
column = np.any(data >= 8, axis=0)
column

array([False, False, False,  True])

In [182]:
data

array([[5, 6, 1, 5],
       [0, 5, 4, 8],
       [3, 7, 5, 9]])

In [183]:
data[1:]

array([[0, 5, 4, 8],
       [3, 7, 5, 9]])

In [184]:
data[:, 2:]

array([[1, 5],
       [4, 8],
       [5, 9]])

In [177]:
data[row]

array([[0, 5, 4, 8],
       [3, 7, 5, 9]])

In [185]:
data[row, column]

array([8, 9])

In [186]:
# quiz 1. 60 ~ 100점 까지 10점 단위로 10 * 5행렬 데이터를 랜덤하게 생성하세요.
# 학생수 10명, 과목수 5과목 

In [188]:
datas = np.random.randint(6, 11, size=(10, 5)) * 10
datas

array([[ 70,  80,  90,  80,  90],
       [100,  60, 100, 100,  80],
       [ 70,  90,  70,  70,  70],
       [ 70,  90,  60,  60,  60],
       [ 80,  60,  90,  60,  90],
       [ 70, 100,  70,  80,  70],
       [ 80,  90,  70,  90,  80],
       [100,  90,  80, 100, 100],
       [ 80,  90,  80, 100,  80],
       [ 80,  90,  80,  90,  90]])

In [ ]:
# quiz 2. 학생별 총점과 평균 데이터를 ndarry로 만드세요.
# datas.shape

In [189]:
datas.shape

(10, 5)

In [208]:
total_data = np.zeros((datas.shape[0], 1))

for idx in range(datas.shape[1]):
    total_data += datas[:, idx:idx+1]

total_data = total_data.reshape(datas.shape[0])
total_data

array([410., 440., 370., 340., 380., 390., 410., 470., 430., 430.])

In [209]:
avg_data = total_data / datas.shape[1]
avg_data

array([82., 88., 74., 68., 76., 78., 82., 94., 86., 86.])

In [211]:
avg_data = np.average(datas, axis=1)
avg_data

array([82., 88., 74., 68., 76., 78., 82., 94., 86., 86.])

In [212]:
# quiz 3. 평균 80점이상이 학생들의 데이터만 출력

In [216]:
datas[avg_data >= 80]

array([[ 70,  80,  90,  80,  90],
       [100,  60, 100, 100,  80],
       [ 80,  90,  70,  90,  80],
       [100,  90,  80, 100, 100],
       [ 80,  90,  80, 100,  80],
       [ 80,  90,  80,  90,  90]])

In [218]:
# c_, r_ : column이나 row로 데이터를 붙일때 사용

In [221]:
data1 = np.array([[1, 2], [3, 4]])
data2 = np.array([5, 6])
data1, data2

(array([[1, 2],
        [3, 4]]),
 array([5, 6]))

In [224]:
np.c_[data1, data2]

array([[1, 2, 5],
       [3, 4, 6]])

In [226]:
np.r_[data1, [data2]]

array([[1, 2],
       [3, 4],
       [5, 6]])

In [227]:
# 총점과 평균을 데이터에 붙이기

In [230]:
total_data, avg_data

(array([410., 440., 370., 340., 380., 390., 410., 470., 430., 430.]),
 array([82., 88., 74., 68., 76., 78., 82., 94., 86., 86.]))

In [232]:
result_data = np.c_[datas, total_data, avg_data] 
result_data

array([[ 70.,  80.,  90.,  80.,  90., 410.,  82.],
       [100.,  60., 100., 100.,  80., 440.,  88.],
       [ 70.,  90.,  70.,  70.,  70., 370.,  74.],
       [ 70.,  90.,  60.,  60.,  60., 340.,  68.],
       [ 80.,  60.,  90.,  60.,  90., 380.,  76.],
       [ 70., 100.,  70.,  80.,  70., 390.,  78.],
       [ 80.,  90.,  70.,  90.,  80., 410.,  82.],
       [100.,  90.,  80., 100., 100., 470.,  94.],
       [ 80.,  90.,  80., 100.,  80., 430.,  86.],
       [ 80.,  90.,  80.,  90.,  90., 430.,  86.]])

In [233]:
import pandas as pd

In [238]:
columns = ["국어", "영어", "수학", "과학", "코딩", "총점", "평균"]
df = pd.DataFrame(result_data, columns=columns)
df = df.astype(np.int)
df

국어   영어   수학   과학   코딩   총점  평균
0   70   80   90   80   90  410  82
1  100   60  100  100   80  440  88
2   70   90   70   70   70  370  74
3   70   90   60   60   60  340  68
4   80   60   90   60   90  380  76
5   70  100   70   80   70  390  78
6   80   90   70   90   80  410  82
7  100   90   80  100  100  470  94
8   80   90   80  100   80  430  86
9   80   90   80   90   90  430  86

In [241]:
df["PASS/FAIL"] = df["평균"].apply(lambda data: "PASS" if data >= 80 else "FAIL")
df

국어   영어   수학   과학   코딩   총점  평균 PASS/FAIL
0   70   80   90   80   90  410  82      PASS
1  100   60  100  100   80  440  88      PASS
2   70   90   70   70   70  370  74      FAIL
3   70   90   60   60   60  340  68      FAIL
4   80   60   90   60   90  380  76      FAIL
5   70  100   70   80   70  390  78      FAIL
6   80   90   70   90   80  410  82      PASS
7  100   90   80  100  100  470  94      PASS
8   80   90   80  100   80  430  86      PASS
9   80   90   80   90   90  430  86      PASS

#### 유용한 함수들
- sum, mean(average), median, var, str, min, max ... 

In [244]:
np.sum(datas)

4070

In [245]:
np.sum(datas, axis=1)

array([410, 440, 370, 340, 380, 390, 410, 470, 430, 430])

In [246]:
np.sum(datas, axis=0)

array([800, 840, 790, 830, 810])

In [247]:
np.mean(datas, axis=0)

array([80., 84., 79., 83., 81.])

In [251]:
data = np.array([1, 2, 3, 4])
np.median(data)

2.5

In [253]:
np.min(datas), np.max(datas)

(60, 100)