#### Numpy Summary

In [5]:
import numpy as np

In [1]:
# 1. ndarray 객체 생성 : Create

In [10]:
arr1 = np.array([1, 2, 3])
arr2 = np.arange(5, 10, 2)
arr3 = np.random.randint(5, 10, size=(2, 3))
arr4 = np.zeros((2, 3))
arr1, arr2, arr3, arr4

(array([1, 2, 3]),
 array([5, 7, 9]),
 array([[8, 6, 7],
        [8, 9, 9]]),
 array([[0., 0., 0.],
        [0., 0., 0.]]))

In [2]:
# 2. ndarray 데이터 선택 : Read, Delete

In [11]:
arr = np.random.randint(5, 10, size=(3, 4))
arr

array([[9, 9, 7, 8],
       [7, 6, 8, 7],
       [6, 8, 5, 6]])

In [14]:
arr[1:][1:], arr[1:, 1:]

(array([[6, 8, 5, 6]]),
 array([[6, 8, 7],
        [8, 5, 6]]))

In [17]:
arr[arr >= 7]

array([9, 9, 7, 8, 7, 8, 7, 8])

In [3]:
# 3. ndarray 데이터 수정 : Update

In [19]:
arr

array([[9, 9, 7, 8],
       [7, 6, 8, 7],
       [6, 8, 5, 6]])

In [21]:
arr[arr >= 7] = 10
arr

array([[10, 10, 10, 10],
       [10,  6, 10, 10],
       [ 6, 10,  5,  6]])

In [4]:
# 4. ndarray 연산

In [22]:
data1 = np.array([1, 2, 3])
data2 = np.array([4, 5, 6])
data3 = np.random.randint(10, size=(2, 3))
data3

array([[9, 3, 0],
       [3, 7, 6]])

In [28]:
# 벡터 * 벡터
data1 + data2

array([5, 7, 9])

In [30]:
# 벡터 * 스칼라
data1 + 10

array([11, 12, 13])

In [32]:
# 매트릭스 * 매트릭스
data3 * data3

array([[81,  9,  0],
       [ 9, 49, 36]])

In [33]:
# 매트릭스 * 벡터
data3 * data1

array([[ 9,  6,  0],
       [ 3, 14, 18]])

In [34]:
data3.shape, data1.shape

((2, 3), (3,))

In [35]:
data4 = np.array([[10], [20]])
data4.shape

(2, 1)

In [37]:
data3 * data4

array([[ 90,  30,   0],
       [ 60, 140, 120]])

In [27]:
# 매트릭스 * 스칼라

In [39]:
data3 * 10

array([[90, 30,  0],
       [30, 70, 60]])