In [3]:
import numpy as np

In [ ]:
ls = [1, 2, 3]
arr = np.array(ls)

type(ls), type(arr), ls, arr

In [ ]:
ls = [1,2,3]
arr = np.array(ls)
arr + arr

In [ ]:
ls + ls, arr + arr

In [ ]:
# 선형대수
# 스칼라(5), 벡터([1, 2, 3]), 매트릭스([[1, 2, 3], [4, 5, 6]])

In [ ]:
arr2 = np.array([[1, 2, 3,1 ], [4, 5, 6, 4], [7, 8, 9, 7],[1, 2, 3, 4]]) 
arr2

In [ ]:
arr2[1][3]

In [ ]:
arr2[1,3]

In [ ]:
arr2.ndim

In [ ]:
# 배열의 차원 확인
arr.ndim, arr2.ndim

In [ ]:
arr2.shape

In [ ]:
# 배열의 모양을 확인
arr.shape, arr2.shape

In [ ]:
arr3 = np.array(list("ABCD"))
arr3

In [ ]:
arr2.dtype

In [ ]:
arr2.astype(np.float64)

In [ ]:
# 배열의 데이터 타입 확인
arr.dtype, arr3.dtype

In [ ]:
# 데이터 타입의 변경
arr4 = arr.astype(np.float)
arr4.dtype

In [ ]:
# np.arange()
# range와 같은 규칙을 갖습니다. 
# 결과 데이터가 ndarray 데이터 타입입니다.

In [ ]:
np.arange(5)

In [ ]:
np.arange(5, 8)

In [ ]:
np.arange(1, 8, 2)

In [ ]:
np.zeros((1,2,2)).ndim

In [ ]:
np.zeros((4,2,2)) #0으로 채워진 행렬데이터를 만들어줌

In [ ]:
zero_data = np.ones((2, 2, 3))
zero_data

#### np.random
- rand() : 균등분포로 난수 발생, 모든 구간에서 동등하게 뽑힌 형태
- randn() : 정규분포로 난수 발생, 중위값을 중심으로 데이터가 모여있는 형태
- randint() : 정수로 난수 발생(균등분포)

In [ ]:
# 균등분포 : uniform : 0 ~ 1 사이의 float 데이터
data = np.random.rand(10)
data

In [ ]:
# 정규분포 : gaussian : 0을 기준으로 float 데이터
data = np.random.randn(10)
data

In [ ]:
# randint : 정수 데이터 타입을 균등분포로 생성

In [ ]:
np.random.randint(5, size=(2, 3))

In [ ]:
np.random.randint(-3, 5, (2, 3))

In [ ]:
np.random.seed(1)
print(np.random.randint(0,100,(10)))
np.random.seed(1)
print(np.random.randint(0,100,(10)))
np.random.seed(1)
print(np.random.randint(0,100,(10)))


In [ ]:
np.random.seed(1)

In [ ]:
np.random.randint(0,100,10)

In [ ]:
np.random.randint(0,100,10)

In [ ]:
np.random.randint(0,100,10)

In [ ]:
# seed()
# numpy의 랜덤값은 seed 값으로 생성 합니다.
# seed 값이 같으면 동일한 랜덤값이 출력됩니다.

In [ ]:
np.random.seed(1)
data1 = np.random.randint(0, 100, 10)

np.random.seed(1)
data2 = np.random.randint(0, 100, 10)

np.random.seed(2)
data3 = np.random.randint(0, 100, 10)

data1, data2, data3

In [ ]:
# choice()
# 특정 범위의 데이터를 랜덤하게 선택하는데 확률 설정이 가능
# 확률 데이터는 모두 합쳤을때 1이 되어야 합니다.

In [ ]:
a = 0.022222222222222223
len(range(1,46))

In [ ]:
np.random.choice(4,5, p=[0.2,0.2,0.2,0.4])

In [ ]:
np.random.choice(10,10,p=[0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1])

In [ ]:
a = 1/45

In [ ]:
a*45

####  2. ndarray 객체에서의 데이터 선택

In [ ]:
data = np.random.randint(5,size=(3,3))

In [ ]:
data

In [ ]:
data[1], data[1][2], data[1,2]
# data[1][2] 와 data[1,2]는 같게나옴. 하지만 나중엔 다른점이 있을예정.

In [ ]:
data2 = np.random.randint(10,size=10)

In [ ]:
data2

In [ ]:
data2[-3],data2[::-2]

In [ ]:
data

In [ ]:
print(data[1:])

print(data[1:][1:])
# data[1:][1:]

In [ ]:
data[1:,1:]

#### 3. ndarray에서 데이터 수정

In [ ]:
data2

In [ ]:
data2[3] = 5

In [ ]:
# vector = vector
data2[3:6] = [11,12,13] #개수가 서로 맞아야 함

In [ ]:
# vector = scala -> broadcasting의 특징을 가짐
data2[3:6] = 20

In [ ]:
data

# matrix = matrix
data[1:,1:] = [[11,12],[13,14]]

# matrix = vector -> broadcasting의 특징을 가짐
data[1:,1:] = 30 

# matrix = scala -> broadcasting의 특징을 가짐
data[1:,1:] = [20,12] 

In [ ]:
data

# reshape()이라는 함수를 사용해서 배열의 차원 변경함

In [ ]:
data = np.random.randint(10,size=(3,4))

In [ ]:
data

In [ ]:
data[data >= 4]

In [ ]:
data = data.reshape(4,-1)

In [ ]:
data = np.zeros_like(data)

In [ ]:
data

In [ ]:
data.reshape(2,6) #행렬 원소의 개수가 맞아야함
# 3*4 == 2*6 

In [ ]:
data.reshape(4,-1)  #두번째 argument에 -1을 넣으면 알아서 숫자에 맞게 변환해줌
data.reshape(3,-1)

In [ ]:
np.zeros_like(data) #모든원소를 0으로 바꾸는 함수

In [ ]:
np.ones_like(data) #모든 원소를 1로 바꾸는 함수

In [ ]:
#ndarray의 연산

In [ ]:
data1 = np.array([1,2,3])
data2 = np.array([1,2,3,4])
data3 = np.random.randint(5,size=(4,3))

In [ ]:
data1,data2,data3

In [ ]:
data3 + data1

In [ ]:
data2.reshape(4,1)

In [ ]:
data2.reshape(-1,2)

In [ ]:
data3 + data2.reshape(4,1)

# 비교연산 :masking :[ ]와 같이 써주면 필터링 기능이 있음

In [ ]:
data

In [ ]:
data >= 2

In [ ]:
data[data >= 2] # []안의 조건에 대해 True인 데이터만 출력해줌 

In [ ]:
data[data >= 2] = 10

In [ ]:
data

# where

In [ ]:
# np.where(condition, {1}, {2})
# condition에 부합하면 {1}실행, 아니면 {2}실행
data = np.random.randint(10, size=(3,3))

In [ ]:
data

In [ ]:
np.where(data<5,0,10)

In [ ]:
# 논리연산 
# all : and : 행렬데이터를 비교 연산한 결과가 하나라도 False 이면 False -> and연산
# any : or : 행렬데이터를 비교 연산한 결과가 하나라도 True 이면 True -> or연산

In [ ]:
data1 = np.array([1,2,3])
data2 = np.array([1,2,3])
data3 = np.array([1,0,3])

In [ ]:
data1 == data2 

In [ ]:
data2 == data3

In [ ]:
np.any(data1==data3)

In [ ]:
np.all(data1 == data2),np.all(data2 == data3)

In [ ]:
np.any(data1 == data2),np.any(data2 == data3)

In [ ]:
data = np.random.randint(10,size=(3,4))

In [ ]:
data

In [ ]:
# 8이상인 데이터가 있는 row만 출력하기
data >= 8

In [ ]:
np.any(data>=8, axis = 1) #axis에 1을 주면 가로축으로 연산을 함
np.any(data>=8, axis = 0) #0이면 세로축으로 연산을 함

In [ ]:
np.any(data>5, axis=1)

In [ ]:
data

In [ ]:
data[np.any(data>=8, axis = 1)] #기본적으로 row에 대해 계산함

In [ ]:
row = np.any(data>=8, axis = 1)

In [ ]:
column = np.any(data>=8, axis = 0)

In [ ]:
data[row]

In [4]:
#quiz 1.60 ~ 100점 까지 10점 단위로 10 * 5 행렬 데이터를 생성하세요
#학생수 10명, 과목수 5과목
datas = np.random.randint(6,11, size=(10,5)) *10

In [5]:
datas

array([[ 80,  90,  90,  90,  80],
       [ 80,  90,  90, 100,  60],
       [ 90,  70,  70,  70,  70],
       [ 80,  90,  90,  70, 100],
       [ 80,  90, 100,  80,  70],
       [100,  90,  80,  80,  90],
       [ 90,  70, 100,  80,  90],
       [ 90, 100, 100,  70,  70],
       [ 60, 100,  90,  90,  60],
       [ 90, 100,  80,  90,  60]])

In [6]:
total = np.zeros((datas.shape[0],1))

for i in range(datas.shape[1]):
    total += datas[:,i:i+1]
avg = total / datas.shape[1]


In [7]:
avg

array([[86.],
       [84.],
       [74.],
       [86.],
       [84.],
       [88.],
       [86.],
       [86.],
       [80.],
       [84.]])

In [8]:
total

array([[430.],
       [420.],
       [370.],
       [430.],
       [420.],
       [440.],
       [430.],
       [430.],
       [400.],
       [420.]])

In [ ]:
#quiz 2. 학생별 총점과 평균 데이터를 ndaary로 만드시오

# SUM = np.any(sum(datas[i], axis = 1)
# AVG = np.any(sum(datas[i]/len(datas[i])), axis = 1)
    


for i in datas:
    a = np.array(sum(i)/5)
    b = np.array(sum(i))

In [ ]:
np.zeros((10,1))

In [ ]:
total_data = np.zeros((datas.shape[0],1))

for i in range(datas.shape[1]):
    total_data += datas[:, i:i+1]
    avg_data = total_data / datas.shape[1]
total_data = total_data.reshape(1,-1)

total_data.reshape(-1,1),avg_data.reshape(-1,1)

In [ ]:
total_data = total_data.reshape(-1,1)
avg_data = avg_data.reshape(-1,1)

In [ ]:
datas[:,:]

In [ ]:
avg_data = np.average(datas,axis=1)
avg_data

In [ ]:
# quiz  평균이 80점 이상인 학생들의 데이터만 출력

In [21]:
for i in range(datas.shape[1]):
    total += datas[:, i:i+1]
    avg_data = total / datas.shape[1]
    np.where(avg[i] > 80, print(datas[i]),print(''))

[80 90 90 90 80]

[ 80  90  90 100  60]

[90 70 70 70 70]

[ 80  90  90  70 100]

[ 80  90 100  80  70]



In [17]:
avg

array([[86.],
       [84.],
       [74.],
       [86.],
       [84.],
       [88.],
       [86.],
       [86.],
       [80.],
       [84.]])

In [ ]:
avg_data >= 80

In [ ]:
datas[avg_data >= 80]

In [ ]:
datas

In [ ]:
# c_, r_ : 컬럼이나 로우로 데이터를 붙일때 사용

In [22]:
data1 = np.array([[1,2],[3,4]])

In [23]:
data2 = np.array([5,6])

In [24]:
data1, data2

(array([[1, 2],
        [3, 4]]),
 array([5, 6]))

In [25]:
np.c_[data1,data2]

array([[1, 2, 5],
       [3, 4, 6]])

In [26]:
np.r_[data1,[data2]]

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
# 총점과 평균을 데이터에 붙이기

In [28]:
total, avg

(array([[4030.],
        [3940.],
        [3510.],
        [4030.],
        [3940.],
        [4160.],
        [4050.],
        [4050.],
        [3720.],
        [3960.]]),
 array([[86.],
        [84.],
        [74.],
        [86.],
        [84.],
        [88.],
        [86.],
        [86.],
        [80.],
        [84.]]))

In [29]:
datas

array([[ 80,  90,  90,  90,  80],
       [ 80,  90,  90, 100,  60],
       [ 90,  70,  70,  70,  70],
       [ 80,  90,  90,  70, 100],
       [ 80,  90, 100,  80,  70],
       [100,  90,  80,  80,  90],
       [ 90,  70, 100,  80,  90],
       [ 90, 100, 100,  70,  70],
       [ 60, 100,  90,  90,  60],
       [ 90, 100,  80,  90,  60]])

In [31]:
result_data = np.c_[datas,total,avg]

In [32]:
result_data

array([[  80.,   90.,   90.,   90.,   80., 4030.,   86.],
       [  80.,   90.,   90.,  100.,   60., 3940.,   84.],
       [  90.,   70.,   70.,   70.,   70., 3510.,   74.],
       [  80.,   90.,   90.,   70.,  100., 4030.,   86.],
       [  80.,   90.,  100.,   80.,   70., 3940.,   84.],
       [ 100.,   90.,   80.,   80.,   90., 4160.,   88.],
       [  90.,   70.,  100.,   80.,   90., 4050.,   86.],
       [  90.,  100.,  100.,   70.,   70., 4050.,   86.],
       [  60.,  100.,   90.,   90.,   60., 3720.,   80.],
       [  90.,  100.,   80.,   90.,   60., 3960.,   84.]])

In [33]:
import pandas as pd

In [36]:
columns = ['국어','영어','수학','과학','코딩','총점','평균']
# df = pd.DataFrame(result_data, columns=columns)
# df = df.astype(np.int)

In [42]:
rows = ['김','이','김','이','김','이','김','이','김','이']

In [38]:
df = pd.DataFrame(result_data, columns=columns)

In [39]:
df

국어     영어     수학     과학     코딩      총점    평균
0   80.0   90.0   90.0   90.0   80.0  4030.0  86.0
1   80.0   90.0   90.0  100.0   60.0  3940.0  84.0
2   90.0   70.0   70.0   70.0   70.0  3510.0  74.0
3   80.0   90.0   90.0   70.0  100.0  4030.0  86.0
4   80.0   90.0  100.0   80.0   70.0  3940.0  84.0
5  100.0   90.0   80.0   80.0   90.0  4160.0  88.0
6   90.0   70.0  100.0   80.0   90.0  4050.0  86.0
7   90.0  100.0  100.0   70.0   70.0  4050.0  86.0
8   60.0  100.0   90.0   90.0   60.0  3720.0  80.0
9   90.0  100.0   80.0   90.0   60.0  3960.0  84.0

In [45]:
df2 = pd.DataFrame(result_data, columns=columns, index=rows)

In [46]:
df2

국어     영어     수학     과학     코딩      총점    평균
김   80.0   90.0   90.0   90.0   80.0  4030.0  86.0
이   80.0   90.0   90.0  100.0   60.0  3940.0  84.0
김   90.0   70.0   70.0   70.0   70.0  3510.0  74.0
이   80.0   90.0   90.0   70.0  100.0  4030.0  86.0
김   80.0   90.0  100.0   80.0   70.0  3940.0  84.0
이  100.0   90.0   80.0   80.0   90.0  4160.0  88.0
김   90.0   70.0  100.0   80.0   90.0  4050.0  86.0
이   90.0  100.0  100.0   70.0   70.0  4050.0  86.0
김   60.0  100.0   90.0   90.0   60.0  3720.0  80.0
이   90.0  100.0   80.0   90.0   60.0  3960.0  84.0

In [ ]:
df["PASS/FAIL"] = df['평균'].apply(lambda data : "PASS" if data >= 80 else "FAIL")

In [ ]:
df

## 유용한 함수들
- sum(합계
- mean(average와 같은 평균) 
- median(중간값)
- var(분산)
- std(표준편차)
- min(최솟값)
- max(최댓값) ...

In [ ]:
np.sum(datas, axis = 1)

In [ ]:
np.mean(datas,axis=0)

In [ ]:
data = np.array([1,2,3,4])

In [ ]:
np.median(data)

In [ ]:
#1 2 3 4 5 6 7
#1 2 4 8 16 32 64
 0 1 2 3 4  5  6

In [ ]:
#     total_data += datas[:, i:i+1]
datas[:,:]